alias: Voron payload available
description: ''
trigger:
  - platform: mqtt
    topic: <instance_name>/klipper/status
condition: []
action:
  - service: mqtt.publish
    data:
      topic: <instance_name>/availability
      payload_template: >-
        {% if "webhooks" in trigger.payload_json.status %}
          {{ trigger.payload_json.status.webhooks.state }}
        {% endif %}
mode: single