- platform: generic
  name: klipper_gcode_preview
  still_image_url: >
    {% if states.sensor.gcode_preview.attributes["relative_path"] == "" %}
        https://<ip_ha>:8123/local/voron.png
    {% else %}
        http://<ip_printer>:7125/server/files/gcodes/{{ states.sensor.gcode_preview.attributes["relative_path"] }}
    {% endif %}
  scan_interval: 5
  content_type: image/png

- platform: mjpeg
  name: Voron Cam
  still_image_url: http://<ip_printer>/webcam/?action=snapshot
  mjpeg_url: http://<ip_printer>/webcam/?action=stream