[mqtt]
address: <ip_of_printer>
port: 1883
#   user name and password_file are only needed if anonymous connexion is
#   not allowed on you mqtt brocker configuration
#username: <mqtt_user>
#password_file: ~/.mqttpass
#   An optional path to a text file containing a password used to log in
#   to the broker.  It is strongly recommended that this file be located
#   in a folder not served by Moonraker.  It is also recommended that the
#   password be unique and not used for other logins, as it is stored in
#   plain text.  To create a password file, one may ssh in to the device
#   and enter the following commands:
#      cd ~
#      echo mypassword > .mqttpass
#   Then set this option to:
#     ~/.mqttpass
#   If this option is omitted no password will be used to login.

mqtt_protocol: v3.1.1

#   the following option is not needed for home assistant sensors
#   you can let it to false 
enable_moonraker_api: False

#   the instance name is the root of the topic
#   replace <instance_name> by the name you want
#   the data are sent in the payload of the following topic:
#   <instance_name>/klipper/status
instance_name: <instance_name>

status_objects:
    webhooks
    heater_bed
    extruder
    print_stats
    toolhead
    display_status
    virtual_sdcard

default_qos: 0